#dist: trusty
sudo: required

services:
    - docker

language: go

go:
    - "1.10.x"

script:
    - go test -v ./...
    - sudo ./docker_test.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        sudo docker push dedis/drand:latest;
    fi

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  #- provider: script
    #script: docker push dedis/drand:$TRAVIS_TAG
    #on:
        #tags: true
        #condition: $TRAVIS_OS_NAME = linux
